"""
Django settings for childhood_canvas_project project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd4lfp((w_un^az#s7n9qq4qr5t_z$e@l^4h+fb4q*o$w78%q3s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts', # see https://learndjango.com/tutorials/django-custom-user-model
    'canvas_app.apps.CanvasAppConfig', # my app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'childhood_canvas_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))], # adds /templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'childhood_canvas_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# https://stackoverflow.com/questions/27886477/invalid-block-tag-static

# DON'T FORGET TO CHANGE ABOVE:
# TEMPLATES  = [    { 
#       ...
#       'DIRS': [ BASE_DIR / 'templates' ], 
#       ... } ]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# DEPLOYMENT NOTES:

# manage.py check --deploy

# Consider: enabling cached template loader...
# https://docs.djangoproject.com/en/2.2/ref/templates/api/#template-loaders
# https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-TEMPLATES

# "If you haven’t set up backups for your database, do it right now!"
# "Now is a good time to check your backup strategy for *MEDIA_ROOT and MEDIA_URL¶* files."

# from https://stackoverflow.com/questions/48913016/django-the-staticfiles-dirs-setting-should-not-contain-the-static-root-setting 
# regarding a search for PythonAnywhere error: 'The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.'
# (seems to be a non-serious debug warning only...)
STATIC_URL = '/static/'
# STATICFILES_DIRS = [ BASE_DIR / 'static' ]
if not DEBUG:
    STATIC_ROOT = ''
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]

# https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/ :
# CSRF_COOKIE_SECURE = True # default False
# SESSION_COOKIE_SECURE = True # # default False
